steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/searce-playground-v1/cloudbuild-webserver:c1', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/searce-playground-v1/cloudbuild-webserver:c1']
  
images: ['asia.gcr.io/searce-playground-v1/cloudbuild-webserver:c1']
logsBucket: 'gs://priya-bucket-for-build-logs'
